In [1]:
pip install scipy

Requirement already satisfied: scipy in c:\users\tomkn\documents\wsl_game\venv\lib\site-packages (1.17.1)
Requirement already satisfied: numpy<2.7,>=1.26.4 in c:\users\tomkn\documents\wsl_game\venv\lib\site-packages (from scipy) (2.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np
from scipy.stats import poisson

In [3]:
pdf = pd.read_csv("data/output/actual/pdf_goals_agg.csv")
total_games = 26
overall_games_played = 5
remaining_games = total_games - overall_games_played

In [4]:

pdf["goals_per_game"] = pdf["goals"] / overall_games_played

In [5]:
pdf

,player_id,goals,full_name,team,goals_per_game
0,WSL_0055,5,Océane Hurtré,Birmingham City,1.0
1,WSL_0231,5,Khadija Shaw,Manchester City,1.0
2,WSL_0308,5,Victoria Pelova,Tottenham Hotspur,1.0
3,WSL_0233,4,Lauren Hemp,Manchester City,0.8
4,WSL_0205,3,Daniëlle van de Donk,London City Lionesses,0.6
5,WSL_0069,3,Kiko Seike,Brighton and Hove Albion,0.6
6,WSL_0320,3,Viviane Asseyi,West Ham,0.6
7,WSL_0349,3,Alexia Putellas,London City Lionesses,0.6
8,WSL_0289,3,Olivia Holdt,Tottenham Hotspur,0.6
9,WSL_0230,2,Mary Fowler,Manchester City,0.4
10,WSL_0274,2,Julia Zigiotti Olme,Manchester United,0.4
11,WSL_0265,2,Melvine Malard,Chelsea,0.4
12,WSL_0337,2,Vivien Endemann,Liverpool,0.4
13,WSL_0356,2,Kadidiatou Diani,London City Lionesses,0.4
14,WSL_0358,2,Lexi Lloyd-Smith,Crystal Palace,0.4
15,WSL_0306,2,Kirsty Hanson,Tottenham Hotspur,0.4
16,WSL_0167,2,Ruby Mace,Everton,0.4
17,WSL_0214,2,Isobel Goodwin,London City Lionesses,0.4
18,WSL_0121,2,Keira Walsh,Chelsea,0.4
19,WSL_0177,2,Cornelia Kapocs,Liverpool,0.4
20,WSL_0110,2,Lauren James,Chelsea,0.4
21,WSL_0174,2,Grace Fisk,Liverpool,0.4
22,WSL_0070,1,Fran Kirby,Brighton and Hove Albion,0.2
23,WSL_0009,1,Smilla Holmberg,Arsenal,0.2
24,WSL_0197,1,Jana Fernández,London City Lionesses,0.2
25,WSL_0193,1,Aurélie Csillag,Liverpool,0.2
26,WSL_0192,1,Alice Bergström,Liverpool,0.2
27,WSL_0180,1,Beata Olsson,Liverpool,0.2
28,WSL_0140,1,Abbie Larkin,Crystal Palace,0.2
29,WSL_0111,1,Alyssa Thompson,Chelsea,0.2
30,WSL_0118,1,Lucy Bronze,Chelsea,0.2
31,WSL_0122,1,Lexi Potter,Chelsea,0.2
32,WSL_0095,1,Jodie Hutton,Charlton Athletic,0.2
33,WSL_0104,1,Ellie Carpenter,Chelsea,0.2
34,WSL_0107,1,Sjoeke Nüsken,Chelsea,0.2
35,WSL_0025,1,Lynn Wilms,Aston Villa,0.2
36,WSL_0052,1,Lily Crosthwaite,Birmingham City,0.2
37,WSL_0027,1,Noelle Maritz,Aston Villa,0.2
38,WSL_0067,1,Maisie Symonds,Brighton and Hove Albion,0.2
39,WSL_0212,1,Delphine Cascarino,London City Lionesses,0.2
40,WSL_0287,1,Signe Gaupset,Tottenham Hotspur,0.2
41,WSL_0285,1,Amanda Nildén,Tottenham Hotspur,0.2
42,WSL_0269,1,Simi Awujo,Manchester United,0.2
43,WSL_0266,1,Elisabeth Terland,Manchester United,0.2
44,WSL_0238,1,Kerstin Casparij,Manchester City,0.2
45,WSL_0202,1,Lucía Corrales,London City Lionesses,0.2
46,WSL_0227,1,Alex Greenwood,Manchester City,0.2
47,WSL_0226,1,Jade Rose,Manchester City,0.2
48,WSL_0307,1,Shekiera Martinez,Tottenham Hotspur,0.2
49,WSL_0305,1,Caitlin Dijkstra,Tottenham Hotspur,0.2
50,WSL_0296,1,Cathinka Tandberg,Tottenham Hotspur,0.2
51,WSL_0339,1,Andrea Medina,Manchester United,0.2
52,WSL_0341,1,Nicole Anyomi,London City Lionesses,0.2
53,WSL_0340,1,Amalie Vangsgaard,Aston Villa,0.2
54,WSL_0355,1,Bethany England,Crystal Palace,0.2
55,WSL_0353,1,Lisa Baum,Arsenal,0.2

In [6]:


pdf["prob_0_goals"] = poisson.pmf(0, pdf["goals_per_game"])
pdf["prob_1_goal"] = poisson.pmf(1, pdf["goals_per_game"])
pdf["prob_2_goals"] = poisson.pmf(2, pdf["goals_per_game"])
pdf["prob_3plus_goals"] = poisson.sf(2, pdf["goals_per_game"])

In [7]:
rng = np.random.default_rng(seed=42)

In [8]:
num_sims = 10000

In [9]:
pdf_temp = pd.DataFrame()

In [10]:
import pandas as pd

simulations = []

for a in range(num_sims):
    pdf_temp = pdf.copy()

    for i in range(remaining_games):
        pdf_temp[f"simulated_goals_week_{i + 1}"] = rng.poisson(
            lam=pdf_temp["goals_per_game"]
        )

    week_cols = [
        f"simulated_goals_week_{i + 1}"
        for i in range(remaining_games)
    ]

    pdf_temp["simulated_goals"] = pdf_temp[week_cols].sum(axis=1)
    pdf_temp["overall_goals"] = (
        pdf_temp["goals"] + pdf_temp["simulated_goals"]
    )
    pdf_temp["sim_number"] = a + 1

    simulations.append(pdf_temp)

pdf_results = pd.concat(simulations, ignore_index=True)

In [11]:
pdf = pdf_results#.query("sim_number == 1")

In [12]:
pdf_pics = pd.read_csv("data/intermediate/actual/player_pics.csv")

In [13]:
a = pdf_pics[["name", "full_name"]].merge(pdf[["full_name", "overall_goals", "sim_number"]], on="full_name")

In [14]:
b = pd.read_csv("data/output/actual/player_pics.csv")[["full_name", "num_picks"]]

In [15]:
c = a.merge(b, on="full_name")

In [16]:
c["points"] = c["overall_goals"] / c["num_picks"]

In [17]:
d = c.groupby(["name", "sim_number"])[["overall_goals", "points"]].sum().sort_values("points", ascending=False).reset_index()

In [18]:
d["rank"] = (
    d.groupby("sim_number")["points"]
    .rank(method="min", ascending=False)
    .astype(int)
)

In [26]:
rank_probabilities = (
    d.groupby(["name", "rank"])
    .size()
    .div(d["sim_number"].nunique())
    .mul(100)
    .unstack(fill_value=0)
    .rename_axis(columns="rank")
    .reset_index()
)

In [31]:
rank_probabilities.sort_values(1, ascending=False).head(20)#.to_csv("data/output/actual/rank_probabilities.csv", index=False)

rank,name,1,2,3,4,5,6,7,8,9,10,11,12,13
9,Samuel Lewis,50.39,23.67,14.71,8.18,1.86,0.82,0.28,0.08,0.01,0.00,0.00,0.00,0.00
3,Holly Tidball,20.77,29.14,26.74,17.50,3.81,1.56,0.40,0.08,0.00,0.00,0.00,0.00,0.00
12,Tom Knuckey,20.00,29.15,28.23,17.17,3.71,1.17,0.38,0.19,0.00,0.00,0.00,0.00,0.00
7,Megan Luxford,9.45,17.75,24.18,31.84,10.44,4.00,1.66,0.55,0.11,0.01,0.00,0.01,0.00
11,Sophie Lewis,0.25,0.86,2.82,9.11,22.48,19.93,18.76,17.24,7.08,0.57,0.80,0.10,0.00
4,Ian Lewis,0.03,0.36,2.34,10.37,35.54,31.34,15.67,3.84,0.46,0.03,0.02,0.00,0.00
8,Paddy Smith,0.02,0.20,0.85,4.73,16.62,19.78,24.09,24.04,9.36,0.19,0.11,0.01,0.00
10,Simon Watson,0.01,0.01,0.11,0.83,2.72,4.70,8.22,15.77,39.55,1.15,22.72,4.12,0.09
0,Alice Teigh,0.00,0.01,0.01,0.47,3.81,16.90,30.24,34.02,12.76,0.79,0.91,0.08,0.00
1,Amy Kanold-Madla,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.05,13.71,86.24
2,Beth Lewis,0.00,0.00,0.00,0.00,0.00,0.00,0.07,1.55,26.05,64.85,7.48,0.00,0.00
5,Janine Lewis,0.00,0.00,0.00,0.00,0.00,0.00,0.07,1.55,26.05,64.85,7.48,0.00,0.00
6,Jessica Luxford,0.00,0.00,0.00,0.00,0.00,0.01,0.07,0.49,3.22,5.53,5.22,73.37,12.09

In [19]:
# e = d.query("rank == 1")

In [20]:
# e.groupby("name")[["sim_number"]].count().reset_index().sort_values("sim_number", ascending=False).rename(columns={"sim_number": "num_wins"})

In [21]:
# num_2 = d.query("rank == 2")
# num_3 = d.query("rank == 3")

In [22]:
# num_2.groupby("name")[["sim_number"]].count().reset_index().sort_values("sim_number", ascending=False).rename(columns={"sim_number": "num_wins"})

In [23]:
# num_3.groupby("name")[["sim_number"]].count().reset_index().sort_values("sim_number", ascending=False).rename(columns={"sim_number": "num_wins"})